services:
  api:
    build:
      context: ./api
    develop:
      watch:
        - action: sync
          path: ./api/
          target: /app/
        - action: rebuild
          path: ./api/package.json
    command: pnpm dev
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://deps_user:deps_pass@db:5432/deps_judge_db
      PROBLEMS_PATH: /data/problems
      DEPS_JUDGE_DOMAIN: deps.rubixdev.net
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./problems:/data/problems:ro
    networks:
      - deps-judge-net

  worker:
    build:
      context: ./worker
    develop:
      watch:
        - action: sync
          path: ./worker/
          target: /app/
        - action: rebuild
          path: ./worker/package.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./problems:/data/problems:ro
      - /tmp/deps-judge:/tmp/deps-judge
    environment:
      DATABASE_URL: postgres://deps_user:deps_pass@db:5432/deps_judge_db
      WORK_DIR: /tmp/deps-judge
    depends_on:
      - db
    networks:
      - deps-judge-net

  db:
    image: postgres:16
    container_name: deps-judge-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: deps_user
      POSTGRES_PASSWORD: deps_pass
      POSTGRES_DB: deps_judge_db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - deps-judge-net

volumes:
  db-data:

networks:
  deps-judge-net:
